### ISSUE TITLE
Unknown instance type  m4.16xlarge

### ISSUE THREAD

**Issue by jayeshdalwadi** [CloudHealth/amazon-pricing#107]
fetch_ec2_instance_pricing] WARNING: encountered Unknown instance type generalCurrentGen m4.16xlarge
[fetch_ec2_instance_pricing] WARNING: encountered Unknown instance type generalCurrentGen m4.16xlarge
[fetch_ec2_instance_pricing] WARNING: encountered Unknown instance type generalCurrentGen m4.16xlarge
AwsPricing::UnknownTypeError: Unknown instance type  m4.16xlarge

it start giveing exception since last few hours it was working earler ?

**Comment by pchaganti** [comment]
#106

**Comment by stanmluke** [comment]
This is a new AWS instance_type, which should now be supported.  Also, changed to ignore new instance_type by handling exception.
